export default {
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  SET_ERRORS: "SET_ERRORS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR"

};
