export default {
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  SET_ERRORS: "SET_ERRORS",
  SET_PASSWORD_MATCH_ERRORS: "SET_PASSWORD_MATCH_ERRORS",
  RESET_FIELD_ERRORS: "RESET_FIELD_ERRORS"
};
